### PR TITLE
Allow reading of translations

### PR DESCRIPTION
**Pull request by TheKeymaster**
This change allows plugin developers to add their own translations for Vue components, using the translation macro and the `TranslationService`.

*somePluginFile.twig*
```twig
{% import "Ceres::PageDesign.Macros.Translations" as Translations %}

{{ Translations.add( "YourPluginName", "Template" ) }}
```

*plugin-entrypoint.js*
```js
window.ceresReadTranslations();
```

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer

@plentymarkets/ceres-io

### CODE REVIEW

**Comment by cjohannsen** [comment]
Hello @TheKeymaster,

thanks for your contribution and sorry for letting you wait that long.
I have one question, why would a plugin need to call the method `readTranslations` again? If you add a file in TWIG, it should be read on pageload.

 
Best regards,
Chris

**Comment by TheKeymaster** [comment]
@cjohannsen thanks for checking!

How would my plugin have to look like if I wanted to make my `Template.properties` available for the Ceres JS `TranslationService`? 

Reading the translations is one of the first things that the Ceres plugin does, and I couldn't really find a way to get around that, except manually reloading the plugin translations.

I would also be up for a PR, where I can tell Ceres to automatically load the translations of my plugin as well. I am not entirely sure about the implementation details, as this could be archived in many different ways. Maybe a custom event such as `BeforeLoad`, which you could listen, and a possibility to call Ceres directly with a `TranslationService`, to add your own translations to the storefront.

```php
// Middleware.php
class Middleware extends \Plenty\Plugin\Middleware
{
    // Constructor, properties, etc.

    /** @var \Ceres\SomeNamespace\TranslationService */
    private $translationService;

    public function before(Request $request)
    {
        $this->eventDispatcher->listen(
            'Ceres.Load.BeforeLoad',
            function () {
                $this->translationService->addTranslationToStorefront('YourPluginName', 'Template');
            }
        );
    }
}
```

**Comment by cjohannsen** [comment]
Hey @TheKeymaster 

if you add this line you posted above `{{ Translations.add( "YourPluginName", "Template" ) }}` it should be enough (if it is placed at the correct location).

If you have access to the forum, we had a thread a few days ago, where a customer had a bug report about that logic:
https://forum.plentymarkets.com/t/mehrfache-translation-add-moeglich/634274

Maybe you have a fault in your code, do you have an example or an repository, that I can check your code?


Best regards,
Chris

**Comment by TheKeymaster** [comment]
@cjohannsen I had placed it in my template, which loads with the `IO.Resources.Import` event, which seems like the right place, as this is just when my JavaScript loads, but apparently at this point it is already too late for Ceres.

After fiddling around some more and also with the link to the forum, I ended up with the following solution:

*src/Middleware.php*
```php
public function before()
{
    $this->eventDispatcher->listen('IO.init.templates', function (Partial $partial) {
        $partial->set('ceres-page-design', 'Ceres::PageDesign.PageDesign');
        $partial->set('page-design', 'MyPlugin::PageDesign.PageDesign');

        return false;
    });
}
```

*resources/views/PageDesign/PageDesign.twig*
```twig
{% extends getPartial('ceres-page-design') %}
{% import "MyPlugin::PageDesign.Macros.Translations" as Translations %}

{# Add plugin translations to Ceres JS #}
{% block PartialFooter %}
    {{ Translations.add( "MyPlugin", "Template" ) }}

    {{ parent() }}
{% endblock %}
```

I am not sure if this is the right solution, but there is no documentation out there, and it is really frustrating spending hours, just to have translations for my Vue components.

It would be awesome if you would improve your documentation, and maybe add some best practices at https://developers.plentymarkets.com.

**Comment by cjohannsen** [comment]
Hello @TheKeymaster since our SSR update, it is not longer a good way to add something to the window object, because it's not available on server side.

If you still have issues with translations in your custom plugin, please don't hesitate to create a thread in our forum.

> It would be awesome if you would improve your documentation, and maybe add some best practices at https://developers.plentymarkets.com.

I forwarded this to our documentation developer.

I will close this request now, thanks for your contribution.

**Pull request closed without merging**
